-- AlterTable
ALTER TABLE `Page` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PageEdit` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Post` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PostEdit` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `SiteChatBot` MODIFY `prompt_template` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `User` MODIFY `username` VARCHAR(191) NOT NULL;
