-- AlterTable
ALTER TABLE `Page` MODIFY `text` TEXT NOT NULL DEFAULT '',
    MODIFY `data` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PageEdit` ADD COLUMN `data` TEXT NOT NULL DEFAULT '',
    MODIFY `text` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Post` MODIFY `text` TEXT NOT NULL DEFAULT '',
    MODIFY `data` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PostEdit` ADD COLUMN `data` TEXT NOT NULL DEFAULT '',
    MODIFY `text` TEXT NOT NULL DEFAULT '';
