-- AlterTable
ALTER TABLE `Bookmark` ADD COLUMN `isTrained` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `Page` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PageEdit` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Post` ADD COLUMN `isTrained` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PostEdit` MODIFY `text` MEDIUMTEXT NOT NULL DEFAULT '',
    MODIFY `data` MEDIUMTEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `SiteChatBot` MODIFY `prompt_template` TEXT NOT NULL DEFAULT '';
