-- AlterTable
ALTER TABLE `Page` ADD COLUMN `access` ENUM('PUBLIC', 'MEMBERS', 'PAID_MEMBERS') NOT NULL DEFAULT 'PUBLIC',
    MODIFY `text` TEXT NOT NULL DEFAULT '',
    MODIFY `data` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PageEdit` MODIFY `text` TEXT NOT NULL DEFAULT '',
    MODIFY `data` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `Post` ADD COLUMN `access` ENUM('PUBLIC', 'MEMBERS', 'PAID_MEMBERS') NOT NULL DEFAULT 'PUBLIC',
    MODIFY `text` TEXT NOT NULL DEFAULT '',
    MODIFY `data` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `PostEdit` MODIFY `text` TEXT NOT NULL DEFAULT '',
    MODIFY `data` TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `UserSite` MODIFY `siteRole` ENUM('BLOCKED', 'USER', 'ADMIN', 'OWNER', 'PAID_USER') NOT NULL DEFAULT 'USER';
